# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-05 07:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hoover',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nvmid', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=50)),
                ('price', models.IntegerField(default=0)),
                ('brand', models.CharField(max_length=50)),
                ('like_count', models.IntegerField(default=0)),
                ('avg_rating', models.FloatField(default=0)),
                ('reg_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('rating', models.IntegerField(default=0)),
                ('pub_date', models.DateTimeField()),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hoover.Hoover')),
            ],
        ),
    ]
