# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-07 15:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hoover', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hoover',
            name='like_count',
        ),
    ]
