# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-07 16:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoover', '0003_auto_20161107_1621'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hoover',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='hoover',
            name='reg_date',
        ),
        migrations.AddField(
            model_name='hoover',
            name='basic_info',
            field=models.CharField(default='hoit', max_length=400),
            preserve_default=False,
        ),
    ]
